### ISSUE TITLE
How can I log between revision ranges?

### ISSUE THREAD

**Issue by TheLudd** [bendrucker/git-log-parser#2]
The git log documentation mentions **revision range** where I can do `git log hash1..hash2` to get all commits between those two. Is it possible to do this with `git-log-parser` and if it is, how?

**Comment by TheLudd** [comment]
Inspected the code and it should be doable by `log.parse(['hash1..hash2'])` but I get no output when doing that. If I execute the same command in the terminal commits are listed...

**Comment by bendrucker** [comment]
Might be able to do it with `{_: 'hash1..hash2'}`. Been a while since I've touched this though. If that's not it I can't help past that. Would welcome a docs PR if you figure it out.

**Comment by TheLudd** [comment]
That was it. Thanks!

**Comment by bendrucker** [comment]
:+1:

**Comment by tannerlinsley** [comment]
🎉  Thanks for this ;)
