### ISSUE TITLE
Invalid commits when folder/file names passed

### ISSUE THREAD

**Issue by valerit** [bendrucker/git-log-parser#5]
When I tried to get all commits made to the folder `app1`, it is returning invalid commits
```
const options = {
	'name-only': true,
	'_': 'app1'
};
```
I think there is an issue in the parser.
```
{ commit: { long: '\napp1/index.js\n', short: undefined },
09:30:37     tree: { long: undefined, short: undefined },
09:30:37     author: { name: undefined, email: undefined, date: Invalid Date },
09:30:37     committer: { name: undefined, email: undefined, date: Invalid Date },
09:30:37     subject: undefined,
09:30:37     body: undefined } ]
```

**Comment by bendrucker** [comment]
Hi, there's a test for this, please try using an argument separator (`--`):

https://github.com/bendrucker/git-log-parser/blob/master/test/index.js#L10-L12

If that doesn't work I'm happy to take a closer look.
